<a href="https://colab.research.google.com/github/SiddharthBloke/RL-Repository/blob/main/Policy_and__value_iteration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
states = [0,1,2,3,4]
action=[0,1]
N_STATES = len(states)
N_ACTIONS = len(action)

In [3]:
print(N_STATES)

5


In [4]:
print(N_ACTIONS)

2


In [5]:
P = np.zeros((N_STATES,N_ACTIONS,N_STATES)) 

In [6]:
print(P)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [7]:
R = np.zeros((N_STATES,N_ACTIONS,N_STATES)) 

In [8]:
print(R)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [9]:
P[0,0,1] =1.0

In [10]:
print(P)

[[[0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [11]:
P[2,0,3] =1.0

In [12]:
print(P)

[[[0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [13]:
P[3,1,4] =1.0

In [14]:
print(P)

[[[0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [15]:
P[4,0,4] =1.0

In [16]:
print(P)

[[[0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1.]]

 [[0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0.]]]


In [17]:
R[0,0,1]=1

In [18]:
print(R)

[[[0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [19]:
R[1,1,2]=10

In [20]:
print(R)

[[[ 0.  1.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0. 10.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]]


In [21]:
R[2,0,3]=100

In [22]:
print(R)

[[[  0.   1.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]]

 [[  0.   0.   0.   0.   0.]
  [  0.   0.  10.   0.   0.]]

 [[  0.   0.   0. 100.   0.]
  [  0.   0.   0.   0.   0.]]

 [[  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]]

 [[  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]]]


In [23]:
R[3,1,4]=1000

In [24]:
print(R)

[[[   0.    1.    0.    0.    0.]
  [   0.    0.    0.    0.    0.]]

 [[   0.    0.    0.    0.    0.]
  [   0.    0.   10.    0.    0.]]

 [[   0.    0.    0.  100.    0.]
  [   0.    0.    0.    0.    0.]]

 [[   0.    0.    0.    0.    0.]
  [   0.    0.    0.    0. 1000.]]

 [[   0.    0.    0.    0.    0.]
  [   0.    0.    0.    0.    0.]]]


In [25]:
R[4,0,4]=1.0

In [26]:
print(R)

[[[   0.    1.    0.    0.    0.]
  [   0.    0.    0.    0.    0.]]

 [[   0.    0.    0.    0.    0.]
  [   0.    0.   10.    0.    0.]]

 [[   0.    0.    0.  100.    0.]
  [   0.    0.    0.    0.    0.]]

 [[   0.    0.    0.    0.    0.]
  [   0.    0.    0.    0. 1000.]]

 [[   0.    0.    0.    0.    1.]
  [   0.    0.    0.    0.    0.]]]


In [27]:
gamma = 0.75

In [28]:
policy  = [0 for s in range (N_STATES)]
V = np.zeros(N_STATES)
print("INTIAL POLICY",policy)

INTIAL POLICY [0, 0, 0, 0, 0]


In [29]:
is_value_changed =True
iterations = 0
while is_value_changed:
   is_value_changed = False
   iterations +=1
  ##run iteration for each state
   for s in range(N_STATES):
    V[s]=sum([P[s,policy[s],s1]*(R[s,policy[s],s1]+ gamma*V[s1]) for s1 in range (N_STATES)])

In [30]:
for s in range (N_STATES):
  q_best = V[s]

In [31]:
print(s)

4


In [32]:
print(q_best)

1.0


In [33]:
for a in range (N_ACTIONS):
  q_sa = sum([P[s,a,s1] * (R[s,a,s1] + gamma * V[s1]) for s1 in range (N_STATES)])
  if q_sa > q_best:
    print("State", s , ":q_sa", q_sa,"q_best", q_best)
    policy[s]=a
    q_best=q_sa
    is_value_changed=True

State 4 :q_sa 1.75 q_best 1.0


In [34]:
print("Iteration:" , iterations)

Iteration: 1


In [35]:
print(q_best)

1.75


In [36]:
print(V)

[  1.   0. 100.   0.   1.]


In [37]:
print(policy)

[0, 0, 0, 0, 0]
