<a href="https://colab.research.google.com/github/SiddharthBloke/RL-Repository/blob/main/QLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
#R matrix
R = np.matrix([[-1,-1,-1,-1,0,-1],
               [-1,-1,-1,0,-1,100],
               [-1,-1,-1,0,-1,-1],
               [-1,0,0,-1,0,-1],
               [-1,0,0,-1,-1,100],
               [-1,0,-1,-1,0,100]])

In [18]:
R

matrix([[ -1,  -1,  -1,  -1,   0,  -1],
        [ -1,  -1,  -1,   0,  -1, 100],
        [ -1,  -1,  -1,   0,  -1,  -1],
        [ -1,   0,   0,  -1,   0,  -1],
        [ -1,   0,   0,  -1,  -1, 100],
        [ -1,   0,  -1,  -1,   0, 100]])

In [19]:
#Q Matrix
Q = np.matrix(np.zeros([6,6]))

In [20]:
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [21]:
gamma = 0.8
initial_state = 1

In [22]:

def available_actions(state):
  current_state_row = R[state]
  av_act = np.where(current_state_row >= 0)[1]
  return av_act

In [23]:
available_act = available_actions(initial_state)

In [24]:
available_act

array([3, 5])

In [25]:

def sample_next_action(available_actions_range):
  next_action = int(np.random.choice(available_act, 1))
  return next_action

In [26]:

action = sample_next_action(available_act)

In [27]:
action

5

In [28]:
#This function updates the Q matrix according to the path selected and the Q learning algoritm
def update(current_state,action,gamma):
  max_index = np.where(Q[action] == np.max(Q[action]))[1]

  if max_index.shape[0]>1 :
    max_index = int(np.random.choice(max_index, size = 1))
  else:
    max_index = int(max_index)
  max_value = Q[action, max_index]

  #Q - Learning Formula
  Q[current_state,action] = R[current_state, action]+ gamma*max_value

#Update Q matrix
update(initial_state,action,gamma)

In [29]:
Q

matrix([[  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0., 100.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.]])

In [30]:
#Training
#train over 10,000 iterations
for i in range(10000):
  current_state = np.random.randint(0,int(Q.shape[0]))
  available_act = available_actions(current_state)
  actions = sample_next_action(available_act)
  update(current_state,action,gamma)


#normalize the trained Q matrix
print("Trained Q matrix:")
print(Q/np.max(Q)*100)


Trained Q matrix:
[[  0.    0.    0.    0.    0.   79.8]
 [  0.    0.    0.    0.    0.  100. ]
 [  0.    0.    0.    0.    0.   79.8]
 [  0.    0.    0.    0.    0.   79.8]
 [  0.    0.    0.    0.    0.  100. ]
 [  0.    0.    0.    0.    0.  100. ]]


In [33]:
current_state = 1
steps = [current_state]

while current_state != 5:
  next_step_index = np.where(Q[current_state,]==np.max(Q[current_state,]))[1]
  if next_step_index.shape[0]>1:
    next_step_index = int(np.random.choice(next_step_index,size=1))
  else:
    next_step_index = int(next_step_index)

  steps.append(next_step_index)
  current_state = next_step_index


print("selected path:")
print(steps)

selected path:
[1, 5]
